plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - INDEX.md
  - BONK.md
  - staff-list.md
  - jane.md
  - jeff.md
  - bank.md
  - cram.md
  - poem1.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md


#collections:
 # staff_members:
  #  output: true
    


theme: jekyll-theme-cayman